# Copyright 2017 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: agones-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gameservers.stable.agones.dev
spec:
  group: stable.agones.dev
  version: v1alpha1
  scope: Namespaced
  names:
    kind: GameServer
    plural: gameservers
    shortNames:
    - gs
    singular: gameserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: agones-controller
  namespace: agones-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stable.agones.dev/role: controller
    spec:
      serviceAccountName: agones-controller
      containers:
      - name: agones-controller
        image: gcr.io/agones-images/agones-controller:0.1
        env:
        # minimum port that can be exposed to GameServer traffic
        - name: MIN_PORT
          value: "7000"
        # maximum port that can be exposed to GameServer traffic
        - name: MAX_PORT
          value: "8000"
        # - name: SIDECAR # overwrite the GameServer sidecar image that is used
        #   value: gcr.io/agones-images/agones-sdk:0.1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
# Service account, secret, role and rolebinding for sidecar (agones-sdk) pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-sdk
secrets:
- name: agones-sdk-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: agones-sdk-secret
  annotations:
    kubernetes.io/service-account.name: agones-sdk
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agones-sdk
  namespace: agones-system
rules:
- apiGroups: ["stable.agones.dev"]
  resources: ["gameservers"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agones-sdk-access
  namespace: agones-system
subjects:
- kind: User
  name: system:serviceaccount:default:agones-sdk
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk
---
# Service account, secret, role and rolebinding for agones-controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-controller
  namespace: agones-system
secrets:
- name: agones-controller-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: agones-controller-secret
  namespace: agones-system
  annotations:
    kubernetes.io/service-account.name: agones-controller
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agones-controller
  namespace: agones-system
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get"]
- apiGroups: ["stable.agones.dev"]
  resources: ["gameservers"]
  verbs: ["delete", "get", "list", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agones-controller-access
  namespace: agones-system
subjects:
- kind: User
  name: system:serviceaccount:agones-system:agones-controller
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-controller
